services:
  - type: web
    name: LedAPP
    env: dotnet
    plan: free  # 可選的計劃，這裡是 Render 的免費層
    buildCommand: "dotnet publish -c Release -o ./publish"
    startCommand: "dotnet ./publish/Led.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production